sudo: false
language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser

services:
  - xvfb

install:
  - npm install

script:
  - npm run build
  - npm run test
